<?php 	
	// 注意key值用小写
	return [
		"/user/index/index"=>"用户首页",
	    "/user/index/getIndexData" => "首页数据",
	    "/user/setting/myinfo" => "个人资料",
	    "/user/setting/updatenickname" => "修改昵称",
	    "/user/setting/authentica" => "实名认证",
	    "/user/setting/safeindex" => "账户安全",
	    "/user/setting/updatephone" => "修改手机",
	    "/user/setting/updatephonevalicode" => "修改手机验证码",
	    "/user/setting/submitpay" => "提交支付密码",
	    "/user/setting/updatepay" => "修改支付密码验证手机号码页面",
	    "/user/setting/updatepaynumber" => "修改支付密码页面",
	    "/user/setting/validphonepay" => "校验修改支付密码操作",
	    "/user/setting/updatesubmitpay" => "修改支付密码操作",
	    "/user/setting/loginpwd" => "设置登录密码页面",
	    "/user/setting/setloginpwd" => "设置登录密码操作",
	    "/user/setting/validloginpwd" => "验证手机号码页面",
	    "/user/setting/updatepwdnumber" => "设置登录密码",
 		"/user/userlogistics/logisticslist"=>"用户收货地址",
 		"/conn/conn/buycon"=>"购物充值",
 		"/conn/conn/buyconlist"=>"购买记录",
 		"/user/apply/applytobus"=>"申请成为商家",
 		"/user/apply/applytomanager"=>"申请成为区代理",
 		"/user/userlogistics/editlogistics"=>'修改用户收货地址',
 		"/user/userlogistics/addlogistics"=>"添加用户收货地址",
	    "/user/index/config"=>'设置',
	    "/user/flow/flowcuslist"=>'交易明细',
	    "/user/flow/flowbuslist"=>"营业额明细",
	    "/user/amount/mycashamount" => "我的余额",
	    "/user/flow/flowreclist" => "现金余额页面",
	    "/user/amount/recharge" => "充值页面",
	    "/user/withdrawals/withdrawalsindex" => "提现页面",
	    "/user/setting/mybanklist" => "银行卡列表页",
	    "/user/setting/addbank" => "添加银行卡",
	    "/user/withdrawals/list" => "提现明细",
// 	    "/user/index/push" => "分享二维码",
	    
	    "/order/index/showorder" => "确认订单",

//		"/user/index/index"=>"用户首页",
		//"/Sys/Pay/paymethod"=>"支付",
// 	    "/user/setting/index"=>"个人中心设置首页",
// 	    "/user/setting/myinfo"=>"我的资料首页",
// 	    "/user/setting/updatenickname"=>"修改昵称",
// 	    "/user/setting/authentica"=>"实名认证",
// 	    "/user/setting/mybanklist"=>"银行卡列表",
// 	    "/user/setting/addbank"=>"添加银行卡",
// 	    "/user/setting/safeindex"=>"账户安全",
// 	    "/user/setting/updatephone"=>"修改用户手机",
// 	    "/user/setting/updatepay"=>"修改支付密码(短信校验页面)",
// 	    "/user/setting/updatepaynumber"=>"修改支付密码",
// 	    "/user/setting/setpay"=>"设置支付密码",
// 	    "/user/index/mybalance"=>"我的余额",
// 	    "/user/index/cashindex"=>"我的牛票页面",
// 	    "/user/index/profitindex"=>"我的牛粮页面",
// 	    "/user/index/bullindex"=>"我的牛豆页面",
// 	    "/user/flow/flowcusindex"=>"交易明细流水列表",
// 	    "/user/flow/futflowindex"=>"待赠明细流水列表",
// 	    "/user/index/mycode"=>"我的二维码",
// 	    "/user/index/myfanslist"=>"牛粉列表"
	];