<?php 	
	// 注意key值用小写
	return [
		"/user/index/index"=>"用户首页",
 		"/user/userlogistics/logisticslist"=>"用户收货地址",
 		"/conn/conn/buycon"=>"购物充值",
 		"/conn/conn/buyconlist"=>"购买记录",
 		"/user/apply/applytobus"=>"申请成为商家",
 		"/user/apply/applytomanager"=>"申请成为区代理",
 		"/user/userlogistics/editlogistics"=>'修改用户收货地址',
 		"/user/userlogistics/addlogistics"=>"添加用户收货地址",
	    "/user/index/config"=>'设置',
	    "/user/flow/flowcuslist"=>'交易明细',
	    "/user/amount/mycashamount" => "我的余额",
	    "/user/withdrawals/withdrawalsindex" => "提现页面",
	    "/user/setting/mybanklist" => "银行卡列表页",
	    "/user/setting/addbank" => "添加银行卡",
	    "/user/withdrawals/list" => "提现明细",
	    "/user/index/push" => "分享二维码",
	    
//		"/user/index/index"=>"用户首页",
		//"/Sys/Pay/paymethod"=>"支付",
// 	    "/user/setting/index"=>"个人中心设置首页",
// 	    "/user/setting/myinfo"=>"我的资料首页",
// 	    "/user/setting/updatenickname"=>"修改昵称",
// 	    "/user/setting/authentica"=>"实名认证",
// 	    "/user/setting/mybanklist"=>"银行卡列表",
// 	    "/user/setting/addbank"=>"添加银行卡",
// 	    "/user/setting/safeindex"=>"账户安全",
// 	    "/user/setting/updatephone"=>"修改用户手机",
// 	    "/user/setting/updatepay"=>"修改支付密码(短信校验页面)",
// 	    "/user/setting/updatepaynumber"=>"修改支付密码",
// 	    "/user/setting/setpay"=>"设置支付密码",
// 	    "/user/index/mybalance"=>"我的余额",
// 	    "/user/index/cashindex"=>"我的牛票页面",
// 	    "/user/index/profitindex"=>"我的牛粮页面",
// 	    "/user/index/bullindex"=>"我的牛豆页面",
// 	    "/user/flow/flowcusindex"=>"交易明细流水列表",
// 	    "/user/flow/futflowindex"=>"待赠明细流水列表",
// 	    "/user/index/mycode"=>"我的二维码",
// 	    "/user/index/myfanslist"=>"牛粉列表"
	];